In [1]:
import numpy as np
import pandas as pd
import json
from typing import Callable

In [35]:
a=[i for i in range(70)]

In [37]:
a=np.array(a)

In [38]:
a=a.reshape(7,10)

In [15]:
a.shape[0]

7

In [39]:
l=np.random.choice(a.shape[0],2,replace=False)

array([3, 1])

In [41]:
a[l]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [12]:
b=np.random.sample(a)

TypeError: only integer scalar arrays can be converted to a scalar index

In [32]:
a=create_grid(5,5)

ValueError: cannot reshape array of size 72 into shape (2,5,5)

In [29]:
l=5
N=5

In [30]:
interval = np.linspace(0, 1, l)
a=np.mgrid[interval, interval]

AttributeError: 'numpy.ndarray' object has no attribute 'step'

In [33]:
a=

In [41]:
a.add(3)

In [46]:
b=[1,2,3,4,5,6,7,8,9]

In [53]:
b[[1,2,3]]

TypeError: list indices must be integers or slices, not list

In [54]:
b=np.array([1,2,3,4,5,6,7,8])

In [57]:
b[np.array(list(a))]

array([2, 3, 4])

In [61]:
name="Iris.csv"

In [62]:
path="data/"+name

In [68]:
reader = pd.read_csv(path, sep = None, iterator = True)
inferred_sep = reader._engine.data.dialect.delimiter

<ipython-input-68-e2eed404c2e9>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  reader = pd.read_csv(path, sep = None, iterator = True)


In [69]:
inferred_sep

';'

In [4]:
with open('parameters.json') as json_file:
        parameters = json.load(json_file)

In [8]:

for i in parameters["distance"]:
    if i=="lp":
        print(i)
    elif i == "mahalanobis":
        print(i)
    elif i == "cosine":
        print(i)
    else:
        raise ValueError("Invalid distance")

lp
lp
lp
cosine
mahalanobis


In [9]:
a="Iris.csv"

In [10]:
a.endswith(".csv")

True

In [11]:
def distance():
    return 5

In [12]:
a=distance

In [17]:
type(distance)==Callable

False

In [21]:
callable(distance)

True